/**
 * Export Addresses and Generate Configuration Files
 */

import * as fs from 'fs';
import * as path from 'path';
import { AllAddresses } from './types';
import { runForgeScript, printSection } from './utils';

export async function exportAddresses(
  rpcUrl: string,
  allAddresses: AllAddresses
): Promise<void> {
  printSection('STEP 5: Exporting Deployed Addresses to JSON');

  // Set all addresses as environment variables for the ExportAddresses script
  const env = {
    WETH_ADDRESS: allAddresses.tokens.WETH,
    USDC_ADDRESS: allAddresses.tokens.USDC,
    DAI_ADDRESS: allAddresses.tokens.DAI,
    USDT_ADDRESS: allAddresses.tokens.USDT,
    GNO_ADDRESS: allAddresses.tokens.GNO,
    UNISWAP_FACTORY: allAddresses.uniswap.factory,
    UNISWAP_ROUTER: allAddresses.uniswap.router,
    PAIR_WETH_USDC: allAddresses.uniswap.pairs.WETH_USDC,
    PAIR_WETH_DAI: allAddresses.uniswap.pairs.WETH_DAI,
    PAIR_WETH_USDT: allAddresses.uniswap.pairs.WETH_USDT,
    PAIR_WETH_GNO: allAddresses.uniswap.pairs.WETH_GNO,
    PAIR_USDC_DAI: allAddresses.uniswap.pairs.USDC_DAI,
    PAIR_USDC_USDT: allAddresses.uniswap.pairs.USDC_USDT,
    PAIR_USDC_GNO: allAddresses.uniswap.pairs.USDC_GNO,
    PAIR_DAI_USDT: allAddresses.uniswap.pairs.DAI_USDT,
    PAIR_DAI_GNO: allAddresses.uniswap.pairs.DAI_GNO,
    PAIR_USDT_GNO: allAddresses.uniswap.pairs.USDT_GNO,
    COW_SETTLEMENT: allAddresses.cowProtocol.settlement,
    COW_AUTHENTICATOR: allAddresses.cowProtocol.authenticator,
    COW_VAULT_RELAYER: allAddresses.cowProtocol.vaultRelayer,
    BALANCER_VAULT: allAddresses.cowProtocol.balancerVault,
    TRADE_SIMULATOR_ADDRESS: allAddresses.auxiliary.tradeSimulator,
    BALANCES_CONTRACT: allAddresses.auxiliary.tradeSimulator,
    SIGNATURES_CONTRACT: allAddresses.auxiliary.signatures,
    HOOKS_TRAMPOLINE: allAddresses.auxiliary.hooksTrampoline,
    COWSHED_IMPLEMENTATION: allAddresses.auxiliary.cowShed.implementation,
    COWSHED_FACTORY: allAddresses.auxiliary.cowShed.factory,
  };

  await runForgeScript(
    'contracts/script/ExportAddresses.s.sol',
    'ExportAddresses',
    rpcUrl,
    '', // No private key needed for view-only script
    {
      broadcast: false,
      verbosity: 2,
      env,
    }
  );

  console.log('');
  console.log('✅ Addresses exported to config/addresses.json');
  console.log('');
}

export async function generateConfigs(allAddresses: AllAddresses): Promise<void> {
  printSection('STEP 6: Generating Configuration Files');

  console.log('Generating configuration files...');

  const configsDir = path.join(__dirname, '../../configs/offline');
  const playgroundDir = path.join(__dirname, '../../../');

  // Ensure directories exist
  fs.mkdirSync(configsDir, { recursive: true });

  // Generate driver.toml
  const driverToml = `app-data-fetching-enabled = true
orderbook-url = "http://orderbook"
tx-gas-limit = "45000000"

[[solver]]
name = "baseline" # Arbitrary name given to this solver, must be unique
endpoint = "http://baseline"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.1" # Percentage in the [0, 1] range
# Anvil account #0 private key (from test mnemonic)
account = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[submission]
gas-price-cap = "1000000000000"

[[submission.mempool]]
mempool = "public"

[contracts]
gp-v2-settlement = "${allAddresses.cowProtocol.settlement}"
weth = "${allAddresses.tokens.WETH}"
balances = "${allAddresses.auxiliary.tradeSimulator}"  # GPv2TradeSimulator
signatures = "${allAddresses.auxiliary.signatures}"

[liquidity]
base-tokens = [
    "${allAddresses.tokens.WETH}", # WETH
    "${allAddresses.tokens.DAI}", # DAI
    "${allAddresses.tokens.USDC}", # USDC
    "${allAddresses.tokens.USDT}", # USDT
    "${allAddresses.tokens.GNO}", # GNO
]

[[liquidity.uniswap-v2]]
router = "${allAddresses.uniswap.router}"
pool-code = "0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f" # Uniswap V2 init code hash
missing-pool-cache-time = "1h"
`;

  fs.writeFileSync(path.join(configsDir, 'driver.toml'), driverToml);
  console.log('  ✅ Generated offline-mode/configs/offline/driver.toml');

  // Generate baseline.toml
  const baselineToml = `chain-id = "31337" # Anvil local chain
base-tokens = [
    "${allAddresses.tokens.WETH}", # WETH
    "${allAddresses.tokens.DAI}", # DAI
    "${allAddresses.tokens.USDC}", # USDC
    "${allAddresses.tokens.USDT}", # USDT
    "${allAddresses.tokens.GNO}", # GNO
]
max-hops = 2
max-partial-attempts = 5
native-token-price-estimation-amount = "100000000000000000" # 0.1 ETH
`;

  fs.writeFileSync(path.join(configsDir, 'baseline.toml'), baselineToml);
  console.log('  ✅ Generated offline-mode/configs/offline/baseline.toml');

  // Generate .env.offline
  const envOffline = `# Auto-generated by deploy-all.ts
# Generated at: ${Math.floor(Date.now() / 1000)}

# Network Configuration
CHAIN_ID=31337
NODE_URL=http://chain:8545
SIMULATION_NODE_URL=http://chain:8545

# Token Addresses
WETH_ADDRESS=${allAddresses.tokens.WETH}
DAI_ADDRESS=${allAddresses.tokens.DAI}
USDC_ADDRESS=${allAddresses.tokens.USDC}
USDT_ADDRESS=${allAddresses.tokens.USDT}
GNO_ADDRESS=${allAddresses.tokens.GNO}
NATIVE_TOKEN_ADDRESS=${allAddresses.tokens.WETH}

# Uniswap V2 Addresses
UNISWAP_V2_FACTORY_ADDRESS=${allAddresses.uniswap.factory}
UNISWAP_V2_ROUTER_ADDRESS=${allAddresses.uniswap.router}

# CoW Protocol Addresses
SETTLEMENT_CONTRACT_ADDRESS=${allAddresses.cowProtocol.settlement}
AUTHENTICATOR_ADDRESS=${allAddresses.cowProtocol.authenticator}
VAULT_RELAYER_ADDRESS=${allAddresses.cowProtocol.vaultRelayer}
BALANCER_VAULT_ADDRESS=${allAddresses.cowProtocol.balancerVault}
BALANCES_CONTRACT_ADDRESS=${allAddresses.auxiliary.tradeSimulator}
SIGNATURES_CONTRACT_ADDRESS=${allAddresses.auxiliary.signatures}
HOOKS_CONTRACT_ADDRESS=${allAddresses.auxiliary.hooksTrampoline}
`;

  fs.writeFileSync(path.join(playgroundDir, '.env.offline'), envOffline);
  console.log('  ✅ Generated playground/.env.offline');

  console.log('');
  console.log('✅ Configuration files generated!');
  console.log('');
}

// If run directly
if (require.main === module) {
  console.error('❌ This script should be run via the main deploy-all.ts script');
  process.exit(1);
}
