/**
 * Generate Configuration Files
 */

import * as fs from 'fs';
import * as path from 'path';
import { AllAddresses } from './types';
import { printSection } from './utils';

export async function generateConfigs(allAddresses: AllAddresses): Promise<void> {
  printSection('STEP 5: Generating Configuration Files');

  console.log('Generating configuration files...');

  const configsDir = path.join(__dirname, '../../configs/offline');
  // In Docker: /playground is mounted, locally: calculate relative path
  const playgroundDir = process.env.DOCKER_ENV ? '/playground' : path.join(__dirname, '../../..');

  // Ensure directories exist
  fs.mkdirSync(configsDir, { recursive: true });

  // Generate driver.toml
  const driverToml = `app-data-fetching-enabled = true
orderbook-url = "http://orderbook"
tx-gas-limit = "45000000"

[[solver]]
name = "baseline" # Arbitrary name given to this solver, must be unique
endpoint = "http://baseline"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.1" # Percentage in the [0, 1] range
# Anvil account #0 private key (from test mnemonic)
account = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[submission]
gas-price-cap = "1000000000000"

[[submission.mempool]]
mempool = "public"

[contracts]
gp-v2-settlement = "${allAddresses.cowProtocol.settlement}"
weth = "${allAddresses.tokens.WETH}"
balances = "${allAddresses.auxiliary.tradeSimulator}"  # GPv2TradeSimulator
signatures = "${allAddresses.auxiliary.signatures}"

[liquidity]
base-tokens = [
    "${allAddresses.tokens.WETH}", # WETH
    "${allAddresses.tokens.DAI}", # DAI
    "${allAddresses.tokens.USDC}", # USDC
    "${allAddresses.tokens.USDT}", # USDT
    "${allAddresses.tokens.GNO}", # GNO
]

[[liquidity.uniswap-v2]]
router = "${allAddresses.uniswap.router}"
pool-code = "0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f" # Uniswap V2 init code hash
missing-pool-cache-time = "1h"
`;

  fs.writeFileSync(path.join(configsDir, 'driver.toml'), driverToml);
  console.log('  ✅ Generated offline-mode/configs/offline/driver.toml');

  // Generate baseline.toml
  const baselineToml = `chain-id = "1" # Mainnet chain ID
base-tokens = [
    "${allAddresses.tokens.WETH}", # WETH
    "${allAddresses.tokens.DAI}", # DAI
    "${allAddresses.tokens.USDC}", # USDC
    "${allAddresses.tokens.USDT}", # USDT
    "${allAddresses.tokens.GNO}", # GNO
]
max-hops = 2
max-partial-attempts = 5
native-token-price-estimation-amount = "100000000000000000" # 0.1 ETH
`;

  fs.writeFileSync(path.join(configsDir, 'baseline.toml'), baselineToml);
  console.log('  ✅ Generated offline-mode/configs/offline/baseline.toml');

  // Generate .env.offline
  const envOffline = `# Auto-generated by deploy-all.ts
# Generated at: ${Math.floor(Date.now() / 1000)}

# Network Configuration
CHAIN_ID=1
NODE_URL=http://chain:8545
SIMULATION_NODE_URL=http://chain:8545

# Token Addresses
WETH_ADDRESS=${allAddresses.tokens.WETH}
DAI_ADDRESS=${allAddresses.tokens.DAI}
USDC_ADDRESS=${allAddresses.tokens.USDC}
USDT_ADDRESS=${allAddresses.tokens.USDT}
GNO_ADDRESS=${allAddresses.tokens.GNO}
NATIVE_TOKEN_ADDRESS=${allAddresses.tokens.WETH}

# Base Tokens for Orderbook
BASE_TOKENS=${allAddresses.tokens.WETH},${allAddresses.tokens.DAI},${allAddresses.tokens.USDC},${allAddresses.tokens.USDT},${allAddresses.tokens.GNO}

# Uniswap V2 Addresses
UNISWAP_V2_FACTORY_ADDRESS=${allAddresses.uniswap.factory}
UNISWAP_V2_ROUTER_ADDRESS=${allAddresses.uniswap.router}

# CoW Protocol Addresses
SETTLEMENT_CONTRACT_ADDRESS=${allAddresses.cowProtocol.settlement}
AUTHENTICATOR_ADDRESS=${allAddresses.cowProtocol.authenticator}
VAULT_RELAYER_ADDRESS=${allAddresses.cowProtocol.vaultRelayer}
BALANCER_VAULT_ADDRESS=${allAddresses.cowProtocol.balancerVault}
BALANCES_CONTRACT_ADDRESS=${allAddresses.auxiliary.tradeSimulator}
SIGNATURES_CONTRACT_ADDRESS=${allAddresses.auxiliary.signatures}
HOOKS_CONTRACT_ADDRESS=${allAddresses.auxiliary.hooksTrampoline}

# CoWShed Addresses
COWSHED_FACTORY_ADDRESS=${allAddresses.auxiliary.cowShed.factory}
COWSHED_IMPLEMENTATION_ADDRESS=${allAddresses.auxiliary.cowShed.implementation}
`;

  fs.writeFileSync(path.join(playgroundDir, '.env.offline'), envOffline);
  console.log('  ✅ Generated playground/.env.offline');

  // Also save a backup to the state directory so it persists with the blockchain state
  const stateDir = path.join(__dirname, '../../state');
  fs.mkdirSync(stateDir, { recursive: true });
  fs.writeFileSync(path.join(stateDir, '.env.offline.backup'), envOffline);
  console.log('  ✅ Backup saved to state/.env.offline.backup');

  console.log('');
  console.log('✅ Configuration files generated!');
  console.log('');
}

// If run directly
if (require.main === module) {
  console.error('❌ This script should be run via the main deploy-all.ts script');
  process.exit(1);
}
